### PR TITLE
ViT Image Classification Support

### PR DESCRIPTION
**Pull request by tanmoyio**
Starter code
```python3
import pytorch_lightning as pl
from transformers import AutoFeatureExtractor

from lightning_transformers.task.vision.image_classification import (
    ImageClassificationDataConfig,
    ImageClassificationDataModule,
    ImageClassificationTransformer,
)

MODEL_NAME = "nateraw/vit-base-beans"
feature_extractor = AutoFeatureExtractor.from_pretrained(pretrained_model_name_or_path=MODEL_NAME)

dm = ImageClassificationDataModule(
    cfg=ImageClassificationDataConfig(
        batch_size=8,
        dataset_name="beans",
        num_workers=8
    ),
    feature_extractor=feature_extractor,
)

model = ImageClassificationTransformer(pretrained_model_name_or_path=MODEL_NAME)
trainer = pl.Trainer(accelerator="gpu", max_epochs=5)
trainer.fit(model, dm)
```

### CODE REVIEW

**Comment by SeanNaren** [comment]
Added some simple tests, the example and we're good to go I think! this is epic, thanks so much @tanmoyio for your contribution ❤️ 

I'm going to assume the VIT model is something you'd like to use, but if you're interested in tackling a Wav2vec task as well it would be great to get your assistance on: https://github.com/PyTorchLightning/lightning-transformers/pull/251

**Comment by tanmoyio** [comment]
@SeanNaren Yeah I would love to add wav2vec2 tasks, may be in another category `speech`

**Comment by SeanNaren** [comment]
> @SeanNaren Yeah I would love to add wav2vec2 tasks, may be in another category `speech`

that sounds perfect! agreed, I think the PR that was made requires a lot of work, might be worth making it from scratch.

**Comment by SeanNaren** [comment]
All fixed! merging this down, thanks so much again 🚀

**Pull request merged**
