### PR TITLE
Use and rename special subset name if provided

### LINKED ISSUE #213: Glue MNLI task fails due to missing 'validation' key in dataset
## 🐛 Bug

MNLI has two validation and two test sets, called `validation_matched`, `validation_mismatched`, `test_matched` and `test_matched`. I assume that this was not taken into account in the datamodule.

### To Reproduce

Run the following command:
```
python train.py task=nlp/text_classification dataset=nlp/text_classification/glue dataset.cfg.dataset_config_name=mnli
```

### Expected behavior

I would expect the dataloader to handle the special case of MNLI and load `validation_matched` and `test_matched` by default. Maybe add an option to additionally test on `test_mismatched` as well, when desired.

### Environment

A standard pip install from source, as of 2021.12.01. Fails with or without GPU.

### PR DESCRIPTION
**Pull request by mariomeissner**
This PR addresses issue, closes #213 

I modify the `load_dataset` function in `core/nlp/data.py` to find and use special subset names if provided, then rename them back to the standard names to avoid failures further along.

Cannot be done in [`[subset]_dataloader`](https://github.com/PyTorchLightning/lightning-transformers/blob/4efda7b4e924b37956c7a008ca01819f5c3f98c8/lightning_transformers/core/data.py#L28) function [as initially proposed](https://github.com/PyTorchLightning/lightning-transformers/issues/213#issuecomment-983970977), because other functions such as [`_select_samples`](https://github.com/PyTorchLightning/lightning-transformers/blob/4efda7b4e924b37956c7a008ca01819f5c3f98c8/lightning_transformers/core/nlp/data.py#L77) are called before that (and would not work well).

Two main reasons for patching `core/nlp/data/py` instead of `core/data.py`:
1. `load_dataset` is not present in the former. Could create a function there and then let the function in the latter call that first... 
2. Never saw this issue happen in speech or vision, it really seems to be an MNLI only thing for now. 

It's up to debate if this should really be moved to `core/data.py` instead.

This PR should likely also include documentation changes, but I didn't check yet how to do that. Pointers appreciated.

I tested the following commands successfully:
```
# A normal glue task without any subset name issues
CUDA_VISIBLE_DEVICES=3 python train.py task=nlp/text_classification dataset=nlp/text_classification/glue dataset.cfg.dataset_config_name=sst2 trainer.val_check_interval=0.01 training.batch_size=128 trainer.gpus=1
```
```
# MNLI issue with renamed subset, smaller validation size and more frequent validation to test that subsampling also works fine
CUDA_VISIBLE_DEVICES=3 python train.py task=nlp/text_classification dataset=nlp/text_classification/glue dataset.cfg.dataset_config_name=mnli ++dataset.cfg.validation_subset_name=validation_matched trainer.val_check_interval=0.01 training.batch_size=128 trainer.gpus=1 ++dataset.cfg.limit_val_samples=256
```

### CODE REVIEW

**Review by Borda — APPROVED** [review]

**Comment by mathemusician** [comment]
For documentation, you could probably write something new [on this page](https://lightning-transformers.readthedocs.io/en/latest/datasets/custom_data.html) by writing something in the [nlp folder](https://github.com/PyTorchLightning/lightning-transformers/tree/master/docs/source/datasets)

Arguably, there would be a separate page for this; but I don't have the credentials to approve/disprove that type of change.

**Comment by mariomeissner** [comment]
So I mentioned it inside "Custom Data Files" for now, but I agree that it's not really the adequate home for it (this is not about custom files). For now I guess it suffices!

**Comment by mathemusician** [comment]
In the documentation, I would add that this works for test and train files too. Something like:

```
Additionally, this works for test and train files as well:

++dataset.cfg.train_subset_name=name_of_subset
++dataset.cfg.test_subset_name=name_of_subset
```

Besides that, I don't see anything else to add.

**Comment by mariomeissner** [comment]
Sorry I missed your last comment @mathemusician. I now added what you suggested.
It seems the CI is failing, but for something unrelated? Let me know if there's anything further to do.

**Comment by mathemusician** [comment]
@mariomeissner Just saw this. @Borda I can fix the CI issue, it's just an import problem. @clementpoiret changed `_TORCH_MAX_VERSION_1_8_1 ` to `_TORCH_MAX_VERSION_SPARSEML`

**Comment by SeanNaren** [comment]
Thank you for this :)

**Pull request merged**
